spring.datasource.url: jdbc:mysql://127.0.0.1:33063/ncuxywka?useSSL=false&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123

#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.show_sql_comments: true

#spring.jpa.hibernate.ddl-auto: create
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

#debug: true

server.servlet.context-path: /ncuxywka
spring.mustache.suffix: .mu

menu:
  items:
  - id: MAIN_ROOMS
    title: Оснвные кмбинеты
    items:
      - id: MAIN
        title: Главная
        url: /
      - id: FAQ
        title: Справочная
        note: FAQ
        url: /faq
      - id: POST_CREO
        title: Лабороторная
        note: Сдать анализы
        url: /creos/draft
      - id: GB
        title: Палата №6
        url: /gb
  - id: FILE_CABINET
    title: Картотека
    items:
      - id: USERS
        title: Пациэнты
        url: /users
      - id: CREOS
        title: Анализы
        url: /creos
      - id: DIAGNOSES
        title: Диагнозы
        url: /diagnoses
  - id: OTHER_ROOMS
    title: Другие палаты
    items:
      - id: WISH_ROOM
        title: Книга желаний
        url: /wish_room
      - id: PETR_ROOM
        title: Похождения поросенка Петра
        url: /petr_room
      - id: FRENIZM_ROOM
        title: Олегофренизмы
        url: /frenizm_room
      - id: MAINSHIT_ROOM
        title: Главсрач
        url: /mainshit_room
      - id: PROCEDURE_ROOM
        title: Процедурная
        url: /proc_room
      - id: NEOFUTURIZM_CREOS
        title: Неофотуризм
        url: /neofuturizm
  - id: USER
    title: Бюллетень
    items:
      - id: SETTINGS
        title: Настройки
        url: /settings
      - id: PERSONAL_MESSAGES
        title: Личные сообщения
        url: /pm
      - id: DIAGNOSES_FROM_ME
        title: Мои диагнозы
        url: /diagnoses?from=%uid
      - id: DIAGNOSES_TO_ME
        title: Диагнозы к моим анализам
        url: /diagnoses?to=%uid
      - id: LOGOUT
        title: Выйти
        url: /logout