spring.datasource.url: jdbc:mysql://127.0.0.1:33063/ncuxywka?useSSL=false&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123

#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.show_sql_comments: true

#spring.jpa.hibernate.ddl-auto: create
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

#debug: true

server.servlet.context-path: /ncuxywka
spring.mustache.suffix: .mu


skin:
  active: original
  templates:
    - id: original
      css: auto_main.css
      img:
        main: main201601.png
        logo: ncuxywka_com.jpg
        lozung: medical_car_green.gif
        gb: gb.jpg
        nizm: nizm.jpg
        mainshit: mainshit.jpg
        proc: proc.jpg
      button:
        creo_comment: Поставить диагноз
        gb_comment: Кря-кря
        vote: Оценить
        creo_select: Добавить этот анализ в мое избранное!
    - id: neo
      css: auto_neo.css
      img:
        main: main201309.png
        lozung: medical_car_green.gif
        logo: neo_ncuxywka_com.png
      button:
        creo_comment: Поставить диагноз
        vote: Оценить
        creo_select: Добавить этот неофутуризм в мое избранное!
    - id: new_year
      css: auto_ny.css
      img:
        main: main201501.gif
        logo: ncuxywka_com_new_year.jpg
        lozung: ny_logo.gif
        gb: gb_ny.jpg
        nizm: nizm_ny.jpg
        mainshit: mainshit_ny.jpg
        proc: proc_ny.jpg
      js_include: snow.js
    - id: first_april
      css: first_april_main.css
      img:
        main: bee/main.jpg
        logo: bee/ncuxywka_com_1apr.jpg
        lozung: bee/lozung.png
        gb: bee/girl.jpg
        nizm: bee/nizm.jpg
        mainshit: bee/mainshit.jpg
        proc: bee/proc.jpg
    - id: feb14
      css: auto_14feb.css
      img:
        main: main_14feb.jpg
        logo: ncuxywka_com_14_feb.jpg
        lozung: lozung_14feb.jpg
        gb: main_14feb.jpg
        nizm: main_14feb.jpg
        mainshit: main_14feb.jpg
        proc: main_14feb.jpg"

menu:
  items:
  - id: MAIN_ROOMS
    title: Оснвные кмбинеты
    items:
      - id: MAIN
        title: Главная
        url: /

      - id: FAQ
        title: Справочная
        note: FAQ
        url: /faq

      - id: POST_CREO
        role: USER
        title: Лабороторная
        note: Сдать анализы
        url: /creos/draft

      - id: REGISTRATION
        role: GUEST
        title: Регистратура
        url: /registration

      - id: GB
        title: Палата №6
        url: /gb

  - id: FILE_CABINET
    title: Картотека
    items:
      - id: USERS
        title: Пациэнты
        url: /users

      - id: CREOS
        title: Анализы
        url: /creos

      - id: QUARANTINE
        title: Карантин
        url: /quarantine

      - id: DIAGNOSES
        title: Диагнозы
        url: /diagnoses

  - id: USER
    title: Бюллетень
    role: USER
    items:
      - id: SETTINGS
        title: Настройки
        url: /settings

      - id: PERSONAL_MESSAGES
        title: Личные сообщения
        url: /pm

      - id: DIAGNOSES_FROM_ME
        title: Мои диагнозы
        url: /diagnoses?from=%uid

      - id: DIAGNOSES_TO_ME
        title: Диагнозы к моим анализам
        url: /diagnoses?to=%uid

      - id: LOGOUT
        title: Выйти
        url: /logout

  - id: OTHER_ROOMS
    title: Другие палаты
    items:
      - id: WISH_ROOM
        title: Книга желаний
        url: /wish_room

      - id: PETR_ROOM
        title: Похождения поросенка Петра
        url: /petr_room

      - id: FRENIZM_ROOM
        title: Олегофренизмы
        url: /frenizm_room

      - id: MAINSHIT_ROOM
        title: Главсрач
        url: /mainshit_room

      - id: PROCEDURE_ROOM
        title: Процедурная
        url: /proc_room

      - id: NEOFUTURIZM_CREOS
        title: Неофотуризм
        url: /neofuturizm

  - id: MAINDOCTOR
    title: Кабинет Главврача
    role: ADMIN
    items:
      - id: RANDOM_CREO
        title: Случайные крео
        url: /lab/random-creo